cache:
  paths:
    - "mise"

steps:
  - label: ":ruby: :rspec: Ruby: RSpec"
    parallelism: 2
    commands:
      - cd rspec
      - bin/test
    soft_fail:
      - exit_status: 1
    plugins:
      - tests#v1.0.0:
          test-runner: rspec
          result-path: tmp/rspec.json
          suite-slug: test-engine-client-examples
          upload-results: false
      - mise#v1.1.4:
          dir: rspec

  - label: ":ruby: Ruby: Minitest"
    parallelism: 2
    commands:
      - cd ruby-minitest
      - bin/test
    soft_fail:
      - exit_status: 1
    plugins:
      - tests#v1.0.0:
          test-runner: custom
          test-cmd: "bundle exec rake test TEST_FILES='{{testExamples}}'"
          test-file-pattern: "**/*_test.rb"
          suite-slug: test-engine-client-examples
          upload-results: false
      - mise#v1.1.4:
          dir: ruby-minitest
    env:
      BUILDKITE_ANALYTICS_LOCATION_PREFIX: ruby-minitest

  - label: ":jest: Jest"
    parallelism: 2
    commands:
      - cd jest
      - bin/test
    soft_fail:
      - exit_status: 1
    plugins:
      - tests#v1.0.0:
          test-runner: jest
          result-path: jest-result.json
          suite-slug: test-engine-client-examples
          upload-results: false
      - mise#v1.1.4:
          dir: jest
    env:
      BUILDKITE_ANALYTICS_LOCATION_PREFIX: jest

  - label: ":cypress: Cypress"
    parallelism: 2
    commands:
      - cd cypress
      - bin/test
    soft_fail:
      - exit_status: 1
    plugins:
      - tests#v1.0.0:
          test-runner: cypress
          suite-slug: test-engine-client-examples
          upload-results: false
      - mise#v1.1.4:
          dir: cypress
          install_system_packages: true

  - label: ":playwright: Playwright"
    parallelism: 2
    commands:
      - cd playwright
      - bin/test
    soft_fail:
      - exit_status: 1
    plugins:
      - tests#v1.0.0:
          test-runner: playwright
          result-path: tmp/playwright-results.json
          suite-slug: test-engine-client-examples
          upload-results: false
      - mise#v1.1.4:
          dir: playwright
    env:
      BUILDKITE_ANALYTICS_LOCATION_PREFIX: playwright

  - label: ":pytest: pytest"
    parallelism: 2
    artifact_paths:
      - pytest/result.json
    commands:
      - cd pytest
      - bin/test
    soft_fail:
      - exit_status: 1
    plugins:
      - tests#v1.0.0:
          test-runner: pytest
          suite-slug: test-engine-client-examples
          upload-results: false
      - mise#v1.1.4:
          dir: pytest

  - label: ":pytest: pytest with (xdist)"
    parallelism: 2
    artifact_paths:
      - pytest/result.json
    commands:
      - cd pytest-xdist
      - bin/test
    soft_fail:
      - exit_status: 1
    plugins:
      - tests#v1.0.0:
          test-runner: pytest
          suite-slug: test-engine-client-examples
          upload-results: false
      - mise#v1.1.4:
          dir: pytest-xdist

  - label: ":swift: Swift: XCTest (test-collector-swift)"
    commands:
      - cd swift-xctest
      - bin/test
    soft_fail:
      - exit_status: 1
    env:
      BUILDKITE_ANALYTICS_TAGS: '{"test.framework.name":"xctest","language.name":"swift","custom.tag.from":"upload"}'
    plugins:
      - cluster-secrets#v1.0.0:
          variables:
            BUILDKITE_ANALYTICS_TOKEN: test_engine_client_examples_suite_token
      - docker#v5.11.0:
          image: "swift:6.0-noble"
          propagate-environment: true
          environment:
            - BUILDKITE_ANALYTICS_TOKEN
            - BUILDKITE_ANALYTICS_TAGS
            - BUILDKITE_ANALYTICS_DEBUG_ENABLED

  - label: ":android: Android"
    commands:
      - cd android
      - bin/test
    soft_fail:
      - exit_status: 1
    plugins:
      - cluster-secrets#v1.0.0:
          variables:
            BUILDKITE_ANALYTICS_TOKEN: test_engine_client_examples_suite_token
      - docker#v5.11.0:
          image: "ghcr.io/cirruslabs/android-sdk:34"
          propagate-environment: true
          environment:
            - BUILDKITE_ANALYTICS_TOKEN

  - label: ":golang: Go test"
    parallelism: 2
    commands:
      - cd go
      - bin/test
    soft_fail:
      - exit_status: 1
    plugins:
      - tests#v1.0.0:
          test-runner: gotest
          result-path: tmp/gotest-result.xml
          suite-slug: test-engine-client-examples
          tags:
            - "language.name=go"
            - "test.framework.name=go-test"
      - mise#v1.1.4:
          dir: go

  - group: "Additional bktec features"
    key: "jest-retry"
    steps:
      - label: ":jest: Jest (Retry Enabled)"
        parallelism: 2
        commands:
          - cd jest
          - bin/test
        soft_fail:
          - exit_status: 1
        plugins:
          - tests#v1.0.0:
              test-runner: jest
              result-path: jest-result.json
              retry-count: 3
              retry-cmd: "npx jest {{testExamples}} --testNamePattern '{{testNamePattern}}' --json --testLocationInResults --outputFile {{resultPath}}"
              suite-slug: test-engine-client-examples
              upload-results: false
          - mise#v1.1.4:
              dir: jest
        env:
          BUILDKITE_ANALYTICS_LOCATION_PREFIX: jest

      - label: ":pytest: pytest (tag filters)"
        parallelism: 2
        artifact_paths:
          - pytest/result.json
        commands:
          - cd pytest-tag-filters
          - bin/test
        soft_fail:
          - exit_status: 1
        plugins:
          - tests#v1.0.0:
              test-runner: pytest
              tag-filters: "component:frontend"
              suite-slug: test-engine-client-examples
              upload-results: false
          - mise#v1.1.4:
              dir: pytest-tag-filters
