steps:
  - label: ":rspec: RSpec"
    parallelism: 2
    command: "bin/test"
    soft_fail: true
    plugins:
      - docker#v5.11.0:
          image: "ruby:3.3-bookworm"
          # Pass required env variables for Buildkite Test Engine Client to the Docker container
          environment:
            - BUILDKITE_BUILD_ID
            - BUILDKITE_JOB_ID
            - BUILDKITE_ORGANIZATION_SLUG
            - BUILDKITE_PARALLEL_JOB
            - BUILDKITE_PARALLEL_JOB_COUNT
            - BUILDKITE_STEP_ID
            - BUILDKITE_TEST_ENGINE_SUITE_SLUG
            - BUILDKITE_TEST_ENGINE_API_ACCESS_TOKEN
      - thedyrt/change-directory#v0.1.1:
          cd: rspec
  
  - label: ":jest: Jest"
    command: "npm install && npm test"
    soft_fail: true
    plugins:
      - docker#v5.11.0:
          image: "node:23.1.0-slim"
      - thedyrt/change-directory#v0.1.1:
          cd: jest
  
  - label: ":cypress: Cypress"
    command: "npm install && npm test"
    soft_fail: true
    plugins:
      - docker#v5.11.0:
          image: "cypress/included:13.15.1"
      - thedyrt/change-directory#v0.1.1:
          cd: cypress

  - label: ":playwright: Playwright"
    command: "npm install && npm test"
    soft_fail: true
    plugins:
      - docker#v5.11.0:
          image: "mcr.microsoft.com/playwright:v1.48.1-noble"
      - thedyrt/change-directory#v0.1.1:
          cd: playwright
