steps:
  - label: ":rspec: RSpec"
    parallelism: 2
    command: "cd rspec && bin/test"
    soft_fail: true
    plugins:
      - cluster-secrets#v1.0.0:
          variables:
            BUILDKITE_ANALYTICS_TOKEN: test_engine_client_examples_suite_token
            BUILDKITE_TEST_ENGINE_API_ACCESS_TOKEN: test_engine_client_examples_api_token
      - docker#v5.11.0:
          image: "ruby:3.3-bookworm"
          # Pass pipeline env variables to the Docker container
          # See https://buildkite.com/docs/test-engine/test-splitting/configuring#using-the-test-engine-client-configure-environment-variables
          propagate-environment: true
          # Pass API access token and Test Engine suite token to the Docker container
          environment:
            - BUILDKITE_ANALYTICS_TOKEN
            - BUILDKITE_TEST_ENGINE_API_ACCESS_TOKEN

  - label: ":jest: Jest"
    parallelism: 2
    command: "cd jest && bin/test"
    soft_fail: true
    plugins:
      - cluster-secrets#v1.0.0:
          variables:
            BUILDKITE_ANALYTICS_TOKEN: test_engine_client_examples_suite_token
            BUILDKITE_TEST_ENGINE_API_ACCESS_TOKEN: test_engine_client_examples_api_token
      - docker#v5.11.0:
          image: "node:23.1.0-bookworm"
          # Pass pipeline env variables to the Docker container
          # See https://buildkite.com/docs/test-engine/test-splitting/configuring#using-the-test-engine-client-configure-environment-variables
          propagate-environment: true
          # Pass API access token and Test Engine suite token to the Docker container
          environment:
            - BUILDKITE_ANALYTICS_TOKEN
            - BUILDKITE_TEST_ENGINE_API_ACCESS_TOKEN

  - label: ":cypress: Cypress"
    parallelism: 2
    command: "cd cypress && bin/test"
    soft_fail: true
    plugins:
      - cluster-secrets#v1.0.0:
          variables:
            BUILDKITE_ANALYTICS_TOKEN: test_engine_client_examples_suite_token
            BUILDKITE_TEST_ENGINE_API_ACCESS_TOKEN: test_engine_client_examples_api_token
      - docker#v5.11.0:
          image: "cypress/included:13.15.1"
          entrypoint: ""
          shell: ["/bin/sh", "-e", "-c"]
          # Pass pipeline env variables to the Docker container
          # See https://buildkite.com/docs/test-engine/test-splitting/configuring#using-the-test-engine-client-configure-environment-variables
          propagate-environment: true
          # Pass API access token and Test Engine suite token to the Docker container
          environment:
            - BUILDKITE_ANALYTICS_TOKEN
            - BUILDKITE_TEST_ENGINE_API_ACCESS_TOKEN

  - label: ":playwright: Playwright"
    parallelism: 2
    command: "cd playwright && bin/test"
    soft_fail: true
    plugins:
      - cluster-secrets#v1.0.0:
          variables:
            BUILDKITE_ANALYTICS_TOKEN: test_engine_client_examples_suite_token
            BUILDKITE_TEST_ENGINE_API_ACCESS_TOKEN: test_engine_client_examples_api_token
      - docker#v5.11.0:
          image: "mcr.microsoft.com/playwright:v1.48.1-noble"
          # Pass pipeline env variables to the Docker container
          # See https://buildkite.com/docs/test-engine/test-splitting/configuring#using-the-test-engine-client-configure-environment-variables
          propagate-environment: true
          # Pass API access token and Test Engine suite token to the Docker container
          environment:
            - BUILDKITE_ANALYTICS_TOKEN
            - BUILDKITE_TEST_ENGINE_API_ACCESS_TOKEN
