steps:
  - label: ":rspec: RSpec"
    parallelism: 2
    command: "bin/test"
    soft_fail: true
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-test-engine-client-examples
      - aws-ssm#v1.0.0:
          parameters:
            BUILDKITE_ANALYTICS_TOKEN: /pipelines/buildkite/test-engine-client-examples/test-engine-suite-token
            BUILDKITE_TEST_ENGINE_API_ACCESS_TOKEN: /pipelines/buildkite/test-engine-client-examples/test-engine-api-access-token
      - docker#v5.11.0:
          image: "ruby:3.3-bookworm"
          # Pass pipeline env variables to the Docker container
          # See https://buildkite.com/docs/test-engine/test-splitting/configuring#using-the-test-engine-client-configure-environment-variables
          propagate-environment: true
          # Pass API access token and Test Engine suite token to the Docker container
          environment:
            - BUILDKITE_ANALYTICS_TOKEN
            - BUILDKITE_TEST_ENGINE_API_ACCESS_TOKEN
      - thedyrt/change-directory#v0.1.1:
          cd: rspec
  
  - label: ":jest: Jest"
    command: "npm install && npm test"
    soft_fail: true
    plugins:
      - docker#v5.11.0:
          image: "node:23.1.0-slim"
      - thedyrt/change-directory#v0.1.1:
          cd: jest
  
  - label: ":cypress: Cypress"
    command: "npm install && npm test"
    soft_fail: true
    plugins:
      - docker#v5.11.0:
          image: "cypress/included:13.15.1"
      - thedyrt/change-directory#v0.1.1:
          cd: cypress

  - label: ":playwright: Playwright"
    command: "npm install && npm test"
    soft_fail: true
    plugins:
      - docker#v5.11.0:
          image: "mcr.microsoft.com/playwright:v1.48.1-noble"
      - thedyrt/change-directory#v0.1.1:
          cd: playwright
