# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "rspec", "~> 3.13"

gem "buildkite-test_collector",
  git: "https://github.com/buildkite/bktest.git",
  ref: "39e98290604af8e1703d26093d8bd33daee5fdec",
  glob: "test-collector-ruby/*.gemspec"
gem "opentelemetry-exporter-otlp", "~> 0.34", require: false
gem "opentelemetry-sdk", "~> 1.13", require: false
