# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "rspec", "~> 3.13"

gem "buildkite-test_collector", git: "https://github.com/buildkite/test-collector-ruby", branch: "per-execution-tags"
